#Конфиг мерчантов
alfa-team:
  url: ""
  token: ""
  key: ""
  secret: ""
alfa-team-white-triangle:
  url: ""
  token: ""
  key: ""
  secret: ""
only-pays:
  url: ""
  secret: ""
  id: ""
evo-pay:
  url: ""
  key: ""
  change-key: ""
nice-pay:
  url: ""
  merchant-id: ""
  secret: ""
honey-money:
  urls:
    main: ""
    token: ""
  secret: ""
  client-id: ""
  sign-key: ""
well-bit:
  url: ""
  secret: ""
  login: ""
  id: ""
  token: ""
croco-pay:
  url: ""
  client-id: ""
  client-secret: ""
bit-zone:
  url: ""
  key: ""
onyx-pay:
  url: ""
  token: ""
  key: ""
  secret: ""
extasy-pay:
  url: ""
  token: ""
pay-lee:
  url: ""
  token: ""
psp-ware:
  url: ""
  token: ""

pay-points:
  url: ""
  token: ""
eze-pay:
  url: ""
  key: ""
  id: ""
panda-pay:
  url: ""
  key: ""
  secret: ""
pay-crown:
  url: ""
  key: ""
  secret: ""
  merchant-id: ""
payscrow:
  url: ""
  key: ""
  high-check-key: ""
  in-house-key: ""
  white-triangle-key: ""
lucky-pay:
  url: ""
  key: ""
appexbit:
  url: ""
  key: ""
mobius:
  url: ""
  token: ""
  merchant-id: ""
ya-pay:
  url: ""
  token: ""
  sign-key: ""
dao-payments:
  url: ""
  key: ""
geo-transfer:
  url: ""
  token: ""
  key: ""
  secret: ""
rostrast:
  token: ""
  key: ""
  secret: ""
  url: ""
fox-pays:
  url: ""
  token: ""
  merchant-id: ""
storm-trade:
  token: ""
  key: ""
  secret: ""
  url: ""
settle-x:
  url: ""
  key: ""
# Конфиг приложения
  sbp-id: ""
  c2c-id: ""
aurora-pay:
  url: ""
  token: ""
  merchant-id: ""
plata-payment:
  url: ""
  token: ""
  merchant-id: ""
plata18:
  url: ""
  token: ""
  merchant-id: ""
neural-pay:
  url: ""
  token: ""
studio:
  url: ""
  key: ""
# Конфиг приложение
springdoc:
  swagger-ui:
    enabled: "true"
    path: "/swagger"
  api-docs:
    path: "/swagger/api-docs"
server:
  port:
spring:
  kafka:
    bootstrap-servers:
  datasource:
    username: ""
    password: ""
    driver-class-name: ""
    url: ""
  jpa:
    hibernate:
      ddl-auto: update
kafka:
  group-id: ''
  topic:
    merchant-details:
      receive: ""
      monitor: ""
      callback: ""
      request: ""
      response: ""
      stop-search: ""
callback-secret: ""
gateway-url: ""
details:
  executor:
    core-pool-size:
    max-pool-size:
    queue-capacity: