#Конфиг мерчантов
alfa-team:
  url: ""
  token: ""
  key: ""
  secret: ""
only-pays:
  url: ""
  secret: ""
  id: ""
evo-pay:
  url: ""
  key: ""
  change-key: ""
nice-pay:
  url: ""
  merchant-id: ""
  secret: ""
honey-money:
  urls:
    main: ""
    token: ""
  secret: ""
  client-id: ""
  sign-key: ""
well-bit:
  url: ""
  secret: ""
  login: ""
  id: ""
  token: ""
croco-pay:
  url: ""
  client-id: ""
  client-secret: ""
bit-zone:
  url: ""
  key: ""
onyx-pay:
  url: ""
  token: ""
  key: ""
  secret: ""
extasy-pay:
  url: ""
  token: ""
pay-lee:
  url: ""
  token: ""
psp-ware:
  url: ""
  token: ""

pay-points:
  url: ""
  token: ""
eze-pay:
  url: ""
  key: ""
  id: ""
panda-pay:
  url: ""
  key: ""
  secret: ""
wwps:
  url: ""
  token: ""
  merchant-id: ""
pay-crown:
  url: ""
  key: ""
  secret: ""
  merchant-id: ""
payscrow:
  url: ""
  key: ""
lucky-pay:
  url: ""
  key: ""
appexbit:
  url: ""
  key: ""
mobius:
  url: ""
  token: ""
  merchant-id: ""
ya-pay:
  url: ""
  token: ""
  sign-key: ""
dao-payments:
  url: ""
  key: ""
geo-transfer:
  url: ""
  token: ""
  key: ""
  secret: ""
rostrast:
  token: ""
  key: ""
  secret: ""
  url: ""
fox-pays:
  url: ""
  token: ""
  merchant-id: ""
# Конфиг приложение
springdoc:
  swagger-ui:
    enabled: "true"
    path: "/swagger"
  api-docs:
    path: "/swagger/api-docs"
server:
  port: